/tf
/tf_static
/cmd_vel
/joint_states
/metrics_refbox/activity_recognition_result
/metrics_refbox/assess_activity_state_result
/metrics_refbox/cluttered_pick_result
/metrics_refbox/command
/metrics_refbox/command_confirmation
/metrics_refbox/gesture_recognition_result
/metrics_refbox/handover_object_result
/metrics_refbox/item_delivery_result
/metrics_refbox/object_detection_result
/metrics_refbox/person_detection_result
/metrics_refbox/receive_object_result
/metrics_refbox_client/activity_recognition_result
/metrics_refbox_client/assess_activity_state_result
/metrics_refbox_client/cluttered_pick_result
/metrics_refbox_client/command
/metrics_refbox_client/gesture_recognition_result
/metrics_refbox_client/handover_object_result
/metrics_refbox_client/item_delivery_result
/metrics_refbox_client/object_detection_result
/metrics_refbox_client/person_detection_result
/metrics_refbox_client/receive_object_result
/rosbag_recorder/event_in
/rosbag_recorder/event_out
/rosbag_recorder/filename
/camera/aligned_depth_to_color/camera_info
/camera/aligned_depth_to_color/image_raw
/camera/color/camera_info
/camera/color/image_raw
